{{- range $name, $svc := .Values.services }}
{{- $render := include "selfcare.renderService" (dict "name" $name "Values" $.Values) }}
{{- if and (eq $render "true") (and (not $.Values.deploy.isolated) $.Values.autoscaling.enabled) }}
{{- $svcObj := merge (deepCopy $.Values.defaultService) $svc }}
{{- $min := $.Values.autoscaling.minReplicas }}
{{- if $svcObj.autoscaling }}{{- $min = $svcObj.autoscaling.minReplicas | default $.Values.autoscaling.minReplicas }}{{- end }}
{{- $max := $.Values.autoscaling.maxReplicas }}
{{- if $svcObj.autoscaling }}{{- $max = $svcObj.autoscaling.maxReplicas | default $.Values.autoscaling.maxReplicas }}{{- end }}
{{- $cpu := $.Values.autoscaling.targetCpu }}
{{- if $svcObj.autoscaling }}{{- $cpu = $svcObj.autoscaling.targetCpu | default $.Values.autoscaling.targetCpu }}{{- end }}
{{- $mem := $.Values.autoscaling.targetMemory }}
{{- if $svcObj.autoscaling }}{{- $mem = $svcObj.autoscaling.targetMemory | default $.Values.autoscaling.targetMemory }}{{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "selfcare.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $min }}
  maxReplicas: {{ $max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpu }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $mem }}
{{- end }}
{{- end }}