{{- if and .Values.podDisruptionBudget.enabled (ne .Values.podDisruptionBudget.enabled "false") }}
{{- if .Values.enabled | default true }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "omobio.fullname" . }}
  namespace: {{ include "omobio.namespace" . }}
  labels:
    {{- include "omobio.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "omobio.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
