{{- range $name, $svc := .Values.services }}
{{- $render := include "selfcare.renderService" (dict "name" $name "Values" $.Values) }}
{{- if eq $render "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "selfcare.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
---
# Shared service account for init jobs / seeders
apiVersion: v1
kind: ServiceAccount
metadata:
  name: selfcare-job-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selfcare.labels" . | nindent 4 }}
automountServiceAccountToken: true