# REGIONAL profile overrides
selfcare:
  security:
    cors:
      allowed-origins: https://admin.reg.selfcare.io

otel:
  enabled: true

logging:
  level:
    com.selfcare: INFO

spring.jpa.show-sql: false
