# STAGING profile overrides
omobio:
  security:
    cors:
      allowed-origins: https://admin.stg.omobio.io

otel:
  enabled: true

logging:
  level:
    com.omobio: INFO

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false
