# PRODUCTION profile overrides
selfcare:
  security:
    cors:
      allowed-origins: https://admin.selfcare.io

otel:
  enabled: true

logging:
  level:
    com.selfcare: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    json:
      enabled: true

spring.jpa.show-sql: false
