package com.omobio.admin.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;

/**
 * Admin user entity for Selfcare Studio (internal portal).
 *
 * Stored in MySQL `admin_users` table.
 * Authentication is SAML 2.0 SSO or local (email/password + MFA).
 *
 * Note: Customer-facing auth is handled by customer-identity-service,
 * NOT this entity. There is no shared user table.
 *
 * The id is a UUID string generated by the application before insert
 * (matches the VARCHAR(64) column in V1 migration).
 */
@Entity
@Table(name = "admin_users", indexes = {
    @Index(name = "ix_admin_users_email", columnList = "email", unique = true),
    @Index(name = "ix_admin_users_tenant_id", columnList = "tenant_id")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AdminUser {

    /** Admin account status. */
    public enum Status {
        ACTIVE,
        /** Awaiting password set or email verification. */
        PENDING_ACTIVATION,
        SUSPENDED,
        DELETED,
        LOCKED
    }

    @Id
    @Column(nullable = false, length = 64)
    private String id;

    @Column(nullable = false, unique = true, length = 256)
    private String email;

    /** Hashed password. Null if authentication is SAML-only. */
    @Column(name = "password_hash", length = 256)
    private String passwordHash;

    @Column(name = "full_name", nullable = false, length = 256)
    private String fullName;

    /**
     * Role: SUPER_ADMIN, TENANT_ADMIN, CONTENT_EDITOR, JOURNEY_BUILDER, etc.
     * Single role field matching the table column.
     */
    @Column(nullable = false, length = 32)
    private String role;

    /** Tenant this admin is scoped to. null = platform-wide (SUPER_ADMIN). */
    @Column(name = "tenant_id", length = 32)
    private String tenantId;

    /** Status: ACTIVE, SUSPENDED, DELETED, LOCKED */
    @Column(nullable = false, length = 32)
    private String status;

    /** Last successful login */
    @Column(name = "last_login_at")
    private Instant lastLoginAt;

    /** IP address of last successful login (for audit). */
    @Column(name = "last_login_ip", length = 45)
    private String lastLoginIp;

    /** Locked until — set after too many failed attempts. */
    @Column(name = "locked_until")
    private Instant lockedUntil;

    /** Last failed login */
    @Column(name = "last_failed_login_at")
    private Instant lastFailedLoginAt;

    /** Number of consecutive failed login attempts */
    @Column(name = "failed_login_count", nullable = false)
    private int failedLoginCount;

    /** MFA type: null, TOTP, SMS, HARDWARE_KEY */
    @Column(name = "mfa_type", length = 32)
    private String mfaType;

    /** Encrypted TOTP secret. Set when mfa_type = TOTP. */
    @Column(name = "mfa_secret", length = 256)
    private String mfaSecret;

    /** If true, MFA must be completed before any action. */
    @Column(name = "mfa_enabled", nullable = false)
    private boolean mfaEnabled;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Column(name = "created_by", length = 64)
    private String createdBy;

    @Column(name = "updated_by", length = 64)
    private String updatedBy;

    public boolean isSuperAdmin() {
        return "SUPER_ADMIN".equals(role);
    }

    public boolean isActive() {
        return Status.ACTIVE.name().equals(status);
    }

    /**
     * Returns the role — exposed for code that expects a getRole() method.
     */
    public String getRole() {
        return role;
    }
}
