FROM eclipse-temurin:25-jre-alpine

WORKDIR /app
RUN addgroup -g 1000 -S selfcare && adduser -u 1000 -S selfcare -G selfcare

ENV JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"

COPY app.jar /app/app.jar
RUN chown selfcare:selfcare /app/app.jar

USER selfcare
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
