FROM eclipse-temurin:25-jre-alpine

ARG MODULE
WORKDIR /app

RUN addgroup -g 1000 -S selfcare && adduser -u 1000 -S selfcare -G selfcare

ENV JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"

COPY target/${MODULE}-1.0.0-SNAPSHOT.jar app.jar

USER selfcare
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
