package com.selfcare.conformance.observability;

import com.selfcare.conformance.utils.AuthHelper;
import com.selfcare.conformance.utils.TestConfig;
import com.selfcare.conformance.utils.TestDataFactory;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.annotations.*;

import static org.assertj.core.api.Assertions.*;
import static org.hamcrest.Matchers.*;

/**
 * Observability conformance tests.
 * Validates correlation ID propagation, tracing headers, and observability contracts.
 *
 * Tests:
 * - Correlation ID echo in response headers
 * - Correlation ID propagation through request chain
 * - X-Request-Id generation when not provided
 * - Correlation ID validation
 * - W3C Trace Context support
 */
@Test(groups = {"observability", "correlation-id"})
public class CorrelationIdTest {

    private static final Logger LOG = LoggerFactory.getLogger(CorrelationIdTest.class);
    private final AuthHelper authHelper = new AuthHelper();

    private AuthHelper.TokenBundle tokenBundle;

    @BeforeClass
    public void setup() {
        tokenBundle = authHelper.login(TestConfig.TENANT_DIALOG, TestDataFactory.uniqueMsisdn());
    }

    @AfterClass
    public void teardown() {
        authHelper.clearCache();
    }

    /**
     * VERIFY: Server echoes back the X-Correlation-Id when provided.
     */
    @Test(description = "Correlation ID is echoed in response header")
    public void correlationId_isEchoedInResponse() {
        LOG.info("=== Testing correlation ID echo ===");
        String correlationId = "conformance-test-" + System.currentTimeMillis();

        Response response = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, correlationId)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        String responseHeader = response.getHeader(TestConfig.CORRELATION_ID_HEADER);
        LOG.info("Sent correlation ID: {}, Received: {}", correlationId, responseHeader);

        assertThat(responseHeader)
                .as("Response must echo back the correlation ID")
                .isEqualTo(correlationId);
    }

    /**
     * VERIFY: Server generates a correlation ID when not provided.
     */
    @Test(description = "Correlation ID is auto-generated when not provided")
    public void correlationId_isAutoGenerated() {
        LOG.info("=== Testing auto-generated correlation ID ===");

        Response response = authHelper.authenticatedRequest(tokenBundle)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        String responseHeader = response.getHeader(TestConfig.CORRELATION_ID_HEADER);
        String requestIdHeader = response.getHeader("X-Request-Id");

        LOG.info("Auto-generated correlation ID: {}", responseHeader);
        LOG.info("X-Request-Id: {}", requestIdHeader);

        // At least one correlation header should be present
        assertThat(responseHeader != null || requestIdHeader != null)
                .as("At least one correlation ID header should be present")
                .isTrue();
    }

    /**
     * VERIFY: Correlation ID appears in error responses.
     */
    @Test(description = "Correlation ID is included in error response body")
    public void correlationId_includedInErrorResponse() {
        LOG.info("=== Testing correlation ID in error responses ===");
        String correlationId = "error-test-" + System.currentTimeMillis();

        Response response = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, correlationId)
                .when()
                .get("/api/v1/nonexistent-endpoint-xyz");

        LOG.info("Error response: status={}, body={}", response.statusCode(), response.getBody().asString());

        response.then()
                .statusCode(404)
                .body("error.correlationId", equalTo(correlationId));
    }

    /**
     * VERIFY: Correlation ID format is valid (UUID or alphanumeric).
     */
    @Test(description = "Correlation ID has valid format")
    public void correlationId_hasValidFormat() {
        LOG.info("=== Testing correlation ID format ===");

        // Test with various formats
        String[] validIds = {
                "conformance-test-12345",
                "550e8400-e29b-41d4-a716-446655440000", // UUID
                "trace.abc.def",
                "simple-alphanumeric-123"
        };

        for (String id : validIds) {
            Response response = authHelper.authenticatedRequest(tokenBundle)
                    .header(TestConfig.CORRELATION_ID_HEADER, id)
                    .queryParam("connectionId", tokenBundle.primaryConnectionId)
                    .when()
                    .get("/api/v1/dashboard/home");

            String responseId = response.getHeader(TestConfig.CORRELATION_ID_HEADER);
            assertThat(responseId)
                    .as("Correlation ID should be echoed back unchanged")
                    .isEqualTo(id);
        }
    }

    /**
     * VERIFY: Special characters in correlation ID are handled.
     */
    @Test(description = "Special characters in correlation ID are handled")
    public void correlationId_handlesSpecialCharacters() {
        LOG.info("=== Testing special characters in correlation ID ===");

        String specialId = "test_123-abc.xyz@example.com";

        Response response = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, specialId)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        String responseId = response.getHeader(TestConfig.CORRELATION_ID_HEADER);
        LOG.info("Special char ID: sent={}, received={}", specialId, responseId);

        // Should echo back (possibly sanitized)
        assertThat(responseId)
                .as("Response should have a correlation ID header")
                .isNotNull();
    }

    /**
     * VERIFY: W3C Trace Context (traceparent) header is supported.
     */
    @Test(description = "W3C Trace Context header is supported")
    public void w3cTraceContext_isSupported() {
        LOG.info("=== Testing W3C Trace Context ===");

        String traceparent = "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01";
        String tracestate = "congo=t61rcWkgMzE";

        Response response = authHelper.authenticatedRequest(tokenBundle)
                .header("traceparent", traceparent)
                .header("tracestate", tracestate)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        String responseTraceparent = response.getHeader("traceparent");
        LOG.info("traceparent: sent={}, received={}", traceparent, responseTraceparent);

        // traceparent should be echoed or new trace ID generated
        assertThat(responseTraceparent != null || response.getHeader(TestConfig.CORRELATION_ID_HEADER) != null)
                .as("Either W3C trace context or correlation ID should be present")
                .isTrue();
    }

    /**
     * VERIFY: Server timing header is included for performance monitoring.
     */
    @Test(description = "Server timing header is included for performance monitoring")
    public void serverTimingHeader_isIncluded() {
        LOG.info("=== Testing Server-Timing header ===");

        Response response = authHelper.authenticatedRequest(tokenBundle)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        String serverTiming = response.getHeader("Server-Timing");
        String xRequestDuration = response.getHeader("X-Request-Duration");

        LOG.info("Server-Timing: {}", serverTiming);
        LOG.info("X-Request-Duration: {}", xRequestDuration);

        // At least one timing header should be present
        assertThat(serverTiming != null || xRequestDuration != null)
                .as("Server should include timing information")
                .isTrue();
    }

    /**
     * VERIFY: Empty correlation ID is rejected or replaced.
     */
    @Test(description = "Empty correlation ID is handled")
    public void emptyCorrelationId_isHandled() {
        LOG.info("=== Testing empty correlation ID ===");

        Response response = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, "")
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        String responseId = response.getHeader(TestConfig.CORRELATION_ID_HEADER);
        LOG.info("Empty correlation ID, response header: {}", responseId);

        // Should be either empty (ignored) or auto-generated
        assertThat(responseId)
                .as("Response should have a non-empty correlation ID")
                .isNotEmpty();
    }

    /**
     * VERIFY: Correlation ID is unique per request.
     */
    @Test(description = "Correlation IDs are unique across requests")
    public void correlationIds_areUnique() {
        LOG.info("=== Testing correlation ID uniqueness ===");

        String id1 = "test-uniqueness-1";
        String id2 = "test-uniqueness-2";
        String id3 = "test-uniqueness-3";

        Response r1 = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, id1)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        Response r2 = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, id2)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        Response r3 = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, id3)
                .queryParam("connectionId", tokenBundle.primaryConnectionId)
                .when()
                .get("/api/v1/dashboard/home");

        assertThat(r1.getHeader(TestConfig.CORRELATION_ID_HEADER)).isEqualTo(id1);
        assertThat(r2.getHeader(TestConfig.CORRELATION_ID_HEADER)).isEqualTo(id2);
        assertThat(r3.getHeader(TestConfig.CORRELATION_ID_HEADER)).isEqualTo(id3);

        // All should be different
        assertThat(r1.getHeader(TestConfig.CORRELATION_ID_HEADER))
                .isNotEqualTo(r2.getHeader(TestConfig.CORRELATION_ID_HEADER));
        assertThat(r2.getHeader(TestConfig.CORRELATION_ID_HEADER))
                .isNotEqualTo(r3.getHeader(TestConfig.CORRELATION_ID_HEADER));
    }

    /**
     * VERIFY: Correlation ID is included in logs and traces.
     */
    @Test(description = "Correlation ID is included in error logs")
    public void correlationId_includedInErrorLogs() {
        LOG.info("=== Testing correlation ID in error logs ===");

        String correlationId = "log-test-" + System.currentTimeMillis();

        // Trigger an error with known correlation ID
        Response response = authHelper.authenticatedRequest(tokenBundle)
                .header(TestConfig.CORRELATION_ID_HEADER, correlationId)
                .when()
                .get("/api/v1/this-does-not-exist");

        response.then().statusCode(404);

        // Verify correlation ID is in the response body for log correlation
        String body = response.getBody().asString();
        assertThat(body)
                .as("Error response should include correlation ID in body")
                .contains(correlationId);
    }
}
